export default {
  BASE_PORT: 12000,
  TESTS: [100, 200, 400, 800],
  REPS: 16,
  WARMUP_DELAY: 3000,
  SERVERS: [
    {
      "#": "Very inefficient and clearly slow. Not worth substantial testing",
      command: "python",
      args: ["./servers/python/http-server.py"],
      name: "Python",
      testLimit: 8,
      protocol: "http",
    },
    {
      "#": "Very inefficient and clearly slow. Not worth substantial testing",
      command: "python",
      args: ["./servers/python/https-server.py"],
      name: "Python",
      testLimit: 8,
      protocol: "https",
    },
    {
      command: "python",
      args: ["./servers/python/http-async.py"],
      name: "Python Async",
      protocol: "http",
    },
    {
      command: "python",
      args: ["./servers/python/http-async-uvloop.py"],
      name: "Python Async (uvloop)",
      protocol: "http",
    },
    {
      command: "python",
      args: ["./servers/python/https-async-uvloop.py"],
      name: "Python Async (uvloop)",
      protocol: "https",
    },
    {
      command: "python",
      args: ["./servers/python/https-async.py"],
      name: "Python Async",
      protocol: "https",
    },
    {
      command: "ruby",
      args: ["./servers/ruby/http-server.rb"],
      name: "Ruby",
      testLimit: 8,
      protocol: "http",
    },
    {
      command: "ruby",
      args: ["./servers/ruby/https-server.rb"],
      name: "Ruby",
      testLimit: 8,
      protocol: "https",
    },
    {
      command: "ruby",
      args: ["./servers/ruby/http-server-async.rb"],
      name: "Ruby Async",
      protocol: "http",
    },
    {
      command: "node",
      args: ["./servers/nodejs/http-server.js"],
      name: "Node",
      protocol: "http",
    },
    {
      command: "node",
      args: ["./servers/nodejs/https-server.js"],
      name: "Node",
      protocol: "https",
    },
    {
      command: "go",
      args: ["run", "./servers/go/http-server.go"],
      name: "Golang",
      protocol: "http",
    },
    {
      command: "go",
      args: ["run", "./servers/go/https-server.go"],
      name: "Golang",
      protocol: "https",
    },
  ],
}
