export default {
  BASE_PORT: 19000,
  TESTS: [4, 8, 16, 32],
  REPS: 1,
  WARMUP_DELAY: 2000,
  SERVERS: [
    {
      "#": "Very inefficient and clearly slow. Not worth substantial testing",
      type: "python",
      command: "python",
      args: ["./servers/python/http-server.py"],
      name: "Python HTTP Server",
      testLimit: 8,
      protocol: "http",
    },
    {
      "#": "Very inefficient and clearly slow. Not worth substantial testing",
      type: "python",
      command: "python",
      args: ["./servers/python/https-server.py"],
      name: "Python HTTPS Server",
      testLimit: 8,
      protocol: "https",
    },
    {
      type: "python",
      command: "python",
      args: ["./servers/python/http-async.py"],
      name: "Python HTTP Async Server",
      protocol: "http",
    },
    {
      type: "python",
      command: "python",
      args: ["./servers/python/http-async-uvloop.py"],
      name: "Python HTTP Async (uvloop) Server",
      protocol: "http",
    },
    {
      type: "python",
      command: "python",
      args: ["./servers/python/https-async-uvloop.py"],
      name: "Python HTTPS Async (uvloop) Server",
      protocol: "https",
    },
    {
      type: "python",
      command: "python",
      args: ["./servers/python/https-async.py"],
      name: "Python HTTPS Async Server",
      protocol: "https",
    },
    {
      type: "ruby",
      command: "ruby",
      args: ["./servers/ruby/http-server.rb"],
      name: "Ruby HTTP Server",
      testLimit: 8,
      protocol: "http",
    },
    {
      type: "ruby",
      command: "ruby",
      args: ["./servers/ruby/https-server.rb"],
      name: "Ruby HTTPS Server",
      testLimit: 8,
      protocol: "https",
    },
    {
      type: "ruby",
      command: "ruby",
      args: ["./servers/ruby/http-server-async.rb"],
      name: "Ruby HTTP Async Server",
      protocol: "http",
    },
    {
      type: "node",
      command: "node",
      args: ["./servers/nodejs/http-server.js"],
      name: "Node HTTP Server",
      protocol: "http",
    },
    {
      type: "node",
      command: "node",
      args: ["./servers/nodejs/https-server.js"],
      name: "Node HTTPS Server",
      protocol: "https",
    },
  ],
}
